language: minimal
os: linux
dist: focal

virt: vm
arch: arm64-graviton2
group: edge

services:
- docker

install:
- export docker=${docker:-docker}
- if test "$docker" == "sudo podman" -o "$docker" == 'podman' ; then . /etc/os-release && echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - && sudo apt-get update -y && sudo apt-get install -y podman containernetworking-plugins ; fi
- if [ "$docker" = 'podman' ] ; then sudo apt-get install -y fuse-overlayfs uidmap slirp4netns ; fi

before_script:
- perl -e 'print map "$_=$ENV{$_}".chr(10), sort keys %ENV'

script:
- $docker load -i local-freeipa-server-$dockerfile.tar
- $docker run --rm --entrypoint rpm local/freeipa-server:$dockerfile -qa | sort
- tests/run-master-and-replica.sh local/freeipa-server:$dockerfile

after_failure:
- $docker ps -aq | while read i ; do $docker rm -f $i ; done
- tests/run-partial-tests.sh Dockerfile.$dockerfile

stages:
- lint
- build
- test
- delivery

jobs:
  include:
    - stage: lint
      install: export docker=${docker:-docker}
      script: |
        result=0
        for dockerfile in Dockerfile.*
        do
          $docker run --rm -it -v "$PWD:/data" -w "/data" hadolint/hadolint /bin/hadolint $dockerfile || result=$(( result + 1 ))
        done
        # exit $result
      after_failure: skip

    - &build-stage
      stage: build
      env: dockerfile=fedora-34
      install: export docker=${docker:-docker}
      script: |
        $docker build -t local/freeipa-server:$dockerfile -f Dockerfile.$dockerfile . \
        && $docker save --output local-freeipa-server-$dockerfile.tar local/freeipa-server:$dockerfile \
        && ( $docker run --rm --interactive --tty --volume /var/run/docker.sock:/var/run/docker.sock:z --volume "$PWD:$PWD:z" -w "$PWD" wagoodman/dive:latest --ci --ci-config .dive-ci.yml local/freeipa-server:$dockerfile || true )
      after_failure: skip
      workspaces:
        create:
          name: fedora-34
          paths:
            - local-freeipa-server-$dockerfile.tar
    - <<: *build-stage
      env: dockerfile=centos-8
      before_script: sed -i 's%registry.centos.org/centos:8%docker.io/arm64v8/centos:8%' Dockerfile.centos-8
      workspaces:
        create:
          name: centos-8
          paths:
            - local-freeipa-server-$dockerfile.tar

    - stage: test
      env: dockerfile=fedora-34 readonly=--read-only seccomp=unconfined
      workspaces:
        use: fedora-34
    - env: dockerfile=centos-8 readonly=--read-only
      workspaces:
        use: centos-8
    - env: dockerfile=centos-8 docker='sudo podman'
      workspaces:
        use: centos-8

    - &test-k3s
      env: dockerfile=fedora-34
      install: skip
      after_failure: skip
      script: tests/run-master-in-k3s.sh local/freeipa-server:$dockerfile local-freeipa-server-$dockerfile.tar
      workspaces:
        use: fedora-34
    - <<: *test-k3s
      env: dockerfile=centos-8
      workspaces:
        use: centos-8

    - &delivery-image
      stage: delivery
      env: dockerfile=fedora-32
      script: |
        # https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
        if [ "$TRAVIS_PULL_REQUEST" == "false" ]
        then
          $docker load -i local-freeipa-server-$dockerfile.tar
          # https://docs.travis-ci.com/user/docker/#private-registry-login
          echo "${DOCKER_PASSWORD}" | $docker login --username "${DOCKER_USERNAME}" --password-stdin "${IMAGE_TAG_BASE%%/*}"
          if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_EVENT_TYPE}" != "pull_request" ];
          then
            export FINAL_TAG="${IMAGE_TAG_BASE}:${dockerfile}";
          else
            export GIT_HASH="$( git rev-parse HEAD 2>/dev/null )";
            export FINAL_TAG="${IMAGE_TAG_BASE}:${dockerfile}-${GIT_HASH}";
          fi
          $docker tag local/freeipa-server:${dockerfile} ${FINAL_TAG} || exit $?
          $docker --log-level debug push ${FINAL_TAG} 2>&1 || exit $?
        else
          echo "INFO: Delivering nothing for Pull Requests"
        fi
      workspaces:
        use: fedora-32
    - <<: *delivery-image
      env: dockerfile=fedora-31
      workspaces:
        use: fedora-31
    - <<: *delivery-image
      env: dockerfile=centos-8
      workspaces:
        use: centos-8
    - <<: *delivery-image
      env: dockerfile=centos-7
      workspaces:
        use: centos-7
    - <<: *delivery-image
      env: dockerfile=fedora-23
      workspaces:
        use: fedora-23
